name: "org1"
version: "1.0"

client:
    organization: org1MSP
    credentialStore:
        path: /Users/kshaik/hyperledger-fabric-network/.hfc-org1 
        cryptoStore:
            path: /Users/kshaik/hyperledger-fabric-network/.hfc-org1 

channels:
    ch1:
        orderers:
            - orderer.hurley.lab
        peers:
            peer0.org1.hurley.lab:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: true
        
            peer0.org2.hurley.lab:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: true
        


organizations:
    org1MSP:
        mspid: org1MSP
        peers:
            - peer0.org1.hurley.lab
        certificateAuthorities:
            - ca.org1.hurley.lab
        adminPrivateKey:
            path: /Users/kshaik/hyperledger-fabric-network/artifacts/crypto-config/peerOrganizations/org1.hurley.lab/users/Admin@org1.hurley.lab/msp/keystore/
        signedCert:
            path: /Users/kshaik/hyperledger-fabric-network/artifacts/crypto-config/peerOrganizations/org1.hurley.lab/users/Admin@org1.hurley.lab/msp/signcerts/

    org2MSP:
        mspid: org2MSP
        peers:
            - peer0.org2.hurley.lab
        certificateAuthorities:
            - ca.org2.hurley.lab
        adminPrivateKey:
            path: /Users/kshaik/hyperledger-fabric-network/artifacts/crypto-config/peerOrganizations/org2.hurley.lab/users/Admin@org2.hurley.lab/msp/keystore/
        signedCert:
            path: /Users/kshaik/hyperledger-fabric-network/artifacts/crypto-config/peerOrganizations/org2.hurley.lab/users/Admin@org2.hurley.lab/msp/signcerts/

orderers:
    orderer.hurley.lab:
        url: grpc://localhost:7050
        grpcOptions:
            ssl-target-name-override: orderer.hurley.lab
            grpc-max-send-message-length: -1
        tlsCACerts:
            path: /Users/kshaik/hyperledger-fabric-network/artifacts/crypto-config/ordererOrganizations/hurley.lab/orderers/orderer.hurley.lab/msp/tlscacerts/tlsca.hurley.lab-cert.pem

peers:
    peer0.org1.hurley.lab:
        url: grpc://localhost:7051
        eventUrl: grpc://localhost:7052
        grpcOptions:
            ssl-target-name-override: peer0.org1.hurley.lab
            grpc.keepalive_time_ms: 600000
        tlsCACerts:
            path: /Users/kshaik/hyperledger-fabric-network/artifacts/crypto-config/peerOrganizations/org1.hurley.lab/peers/peer0.org1.hurley.lab/msp/tlscacerts/tlsca.org1.hurley.lab-cert.pem

    peer0.org2.hurley.lab:
        url: grpc://localhost:7151
        eventUrl: grpc://localhost:7152
        grpcOptions:
            ssl-target-name-override: peer0.org2.hurley.lab
            grpc.keepalive_time_ms: 600000
        tlsCACerts:
            path: /Users/kshaik/hyperledger-fabric-network/artifacts/crypto-config/peerOrganizations/org2.hurley.lab/peers/peer0.org2.hurley.lab/msp/tlscacerts/tlsca.org2.hurley.lab-cert.pem

certificateAuthorities:
    ca.org1.hurley.lab:
        url: http://localhost:7054
        httpOptions:
            verify: false
        tlsCACerts:
            path: /Users/kshaik/hyperledger-fabric-network/artifacts/crypto-config/peerOrganizations/org1.hurley.lab/ca/ca.org1.hurley.lab-cert.pem
        registrar:
            - enrollId: admin
              enrollSecret: adminpw
        caName: ca.org1.hurley.lab

    ca.org2.hurley.lab:
        url: http://localhost:7154
        httpOptions:
            verify: false
        tlsCACerts:
            path: /Users/kshaik/hyperledger-fabric-network/artifacts/crypto-config/peerOrganizations/org2.hurley.lab/ca/ca.org2.hurley.lab-cert.pem
        registrar:
            - enrollId: admin
              enrollSecret: adminpw
        caName: ca.org2.hurley.lab

  